---
spring:
  web.resources.static-locations: "file:./app"
  
server.servlet.encoding:
  charset: UTF-8
  force: true
  
cds:
  odata-v4.endpoint.path: "/api"
  messaging.services:
    bupa-messaging:
      kind: file-based-messaging
      binding: '/Users/d040506/git/cap/samples/messaging.txt'
  security.mock.users:
    - name: admin
      password: admin
      roles:
      - admin
      attributes:
        businessPartner:
        - "10401010"
    - name: user
      password: user
      
---
spring:
  config.activate.on-profile: remote-service

cds:
  remote.services:
    - name: ReviewService

---
spring:
  config.activate.on-profile: cloud
cds:
  messaging.services:
    bupa-messaging:
      kind: enterprise-messaging
      topic-namespace: sap/S4HANAOD/dkom
  remote.services:
  - name: API_BUSINESS_PARTNER
    destination:
      name: "s4-business-partner-api"
      suffix: "/sap/opu/odata/sap"
      type: "odata-v2"
api-hub:
  api-key: "" # Place API Key from SAP API Business Hub here

---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
